<a href="https://colab.research.google.com/github/newmantic/HJM/blob/main/HJM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def generate_forward_curve(initial_curve, volatility, time_horizon, num_steps, num_simulations):
    """
    Generate forward rate curves using the HJM model.

    Args:
        initial_curve (np.array): The initial forward rate curve.
        volatility (float): Constant volatility for the forward rates.
        time_horizon (float): The total time horizon for the simulation.
        num_steps (int): The number of time steps in the simulation.
        num_simulations (int): The number of simulated forward curves.

    Returns:
        np.ndarray: Simulated forward rate curves of shape (num_simulations, num_steps, len(initial_curve)).
    """
    dt = time_horizon / num_steps
    num_maturities = len(initial_curve)

    # Initialize an array to hold all the simulated forward curves
    forward_curves = np.zeros((num_simulations, num_steps, num_maturities))

    # Set the initial forward curve for all simulations
    forward_curves[:, 0, :] = initial_curve

    # Simulate the evolution of the forward curves
    for i in range(1, num_steps):
        dW = np.random.normal(0, np.sqrt(dt), (num_simulations, num_maturities))
        forward_curves[:, i, :] = forward_curves[:, i-1, :] + volatility * dW

    return forward_curves

In [2]:
# Example parameters
initial_forward_curve = np.array([0.02, 0.025, 0.03, 0.035, 0.04])  # Initial forward rates for different maturities
volatility = 0.01  # Constant volatility
time_horizon = 1.0  # Total time horizon in years
num_steps = 10  # Number of time steps in the simulation
num_simulations = 5  # Number of simulated forward curves

# Generate the forward curves
simulated_forward_curves = generate_forward_curve(initial_forward_curve, volatility, time_horizon, num_steps, num_simulations)

# Analyze the results
print("Simulated Forward Curves:")
print(simulated_forward_curves)

Simulated Forward Curves:
[[[0.02       0.025      0.03       0.035      0.04      ]
  [0.01998302 0.02796009 0.03312877 0.03595518 0.03943845]
  [0.02132334 0.02887237 0.0341183  0.03415422 0.04174378]
  [0.02067726 0.03577418 0.03446629 0.03503339 0.04214422]
  [0.01562237 0.0326469  0.03485291 0.03476819 0.04266733]
  [0.01735347 0.03385888 0.03736787 0.03220366 0.0426849 ]
  [0.01642816 0.03164304 0.03733171 0.03038767 0.04293509]
  [0.01271271 0.03314302 0.03395427 0.02830286 0.04302872]
  [0.01188058 0.03517884 0.03204008 0.03274018 0.04334592]
  [0.01347362 0.038625   0.03322884 0.03214065 0.04244723]]

 [[0.02       0.025      0.03       0.035      0.04      ]
  [0.02644753 0.02194587 0.03057058 0.03033265 0.0387098 ]
  [0.02568486 0.02083669 0.0304733  0.03299467 0.0391387 ]
  [0.02230291 0.02611322 0.03237671 0.02664577 0.03892982]
  [0.01833156 0.02245656 0.03438494 0.0217737  0.04023569]
  [0.01691711 0.0179018  0.03389082 0.02177884 0.04239536]
  [0.01510012 0.01712239 0.0